name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build Project and Prepare Android
        run: |
          TARGET_DIR=$(find . -name "package.json" -not -path "*/node_modules/*" -exec dirname {} \;)
          echo "Project directory is: $TARGET_DIR"
          cd "$TARGET_DIR"

          npm install
          npm run build
          
          npm install @capacitor/android @capacitor/core @capacitor/cli
          if [ ! -d "android" ]; then
            npx cap add android
          fi
          npx cap sync android

      - name: Build Android APK
        run: |
          TARGET_DIR=$(find . -name "package.json" -not -path "*/node_modules/*" -exec dirname {} \;)
          cd "$TARGET_DIR"
          
          if [ -d "android" ]; then
            cd android
            chmod +x gradlew
            ./gradlew assembleDebug
          else
            echo "Android folder build failed!"
            exit 1
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: game-apk
          path: '**/android/app/build/outputs/apk/debug/app-debug.apk'
